apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: novapay-alerts
  namespace: monitoring
spec:
  groups:
  - name: novapay.rules
    rules:

    # 🚨 Pod Down Alert
    - alert: PodDown
      expr: kube_pod_status_ready{condition="false"} == 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod is DOWN in NovaPay cluster"
        description: "A pod is not in ready state"

    # 🚨 High CPU Usage
    - alert: HighCPUUsage
      expr: (100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected"
        description: "CPU usage is above 80%"

    # 🚨 High Memory Usage
    - alert: HighMemoryUsage
      expr: ((1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High Memory usage detected"
        description: "Memory usage is above 80%"
